# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['c_name']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['i_name']},
        ),
    ]
