# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0003_auto_20171027_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rathirohitbill_inven',
            name='Billing',
        ),
        migrations.RemoveField(
            model_name='rathirohitbill_inven',
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='rathirohitbilling',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='rathirohitBill_Inven',
        ),
        migrations.DeleteModel(
            name='rathirohitBilling',
        ),
        migrations.DeleteModel(
            name='rathirohitCustomer',
        ),
        migrations.DeleteModel(
            name='rathirohitInventory',
        ),
    ]
