# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0009_auto_20171028_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qwertybill_inven',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qwertybilling',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qwertycustomer',
            options={'managed': False, 'ordering': ['c_name']},
        ),
        migrations.AlterModelOptions(
            name='qwertyinventory',
            options={'managed': False, 'ordering': ['i_name']},
        ),
    ]
