# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0012_auto_20171028_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samrbill_inven',
            name='Billing',
        ),
        migrations.RemoveField(
            model_name='samrbill_inven',
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='samrbilling',
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='rathirohitbill_inven',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rathirohitbilling',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rathirohitcustomer',
            options={'managed': True, 'ordering': ['c_name']},
        ),
        migrations.AlterModelOptions(
            name='rathirohitinventory',
            options={'managed': True, 'ordering': ['i_name']},
        ),
        migrations.DeleteModel(
            name='SAMRBill_Inven',
        ),
        migrations.DeleteModel(
            name='SAMRBilling',
        ),
        migrations.DeleteModel(
            name='SAMRCustomer',
        ),
        migrations.DeleteModel(
            name='SAMRInventory',
        ),
    ]
