# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0013_auto_20171028_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onk_rbill_inven',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='onk_rbilling',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='onk_rcustomer',
            options={'managed': True, 'ordering': ['c_name']},
        ),
        migrations.AlterModelOptions(
            name='onk_rinventory',
            options={'managed': True, 'ordering': ['i_name']},
        ),
        migrations.AlterField(
            model_name='rathirohitbilling',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='DashBoard.rathirohitCustomer'),
        ),
        migrations.AlterField(
            model_name='rathirohitbilling',
            name='saletime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
