# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0015_auto_20171028_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qwertybill_inven',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qwertybilling',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qwertycustomer',
            options={'managed': True, 'ordering': ['c_name']},
        ),
        migrations.AlterModelOptions(
            name='qwertyinventory',
            options={'managed': True, 'ordering': ['i_name']},
        ),
        migrations.AlterField(
            model_name='guestbilling',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='DashBoard.guestCustomer'),
        ),
        migrations.AlterField(
            model_name='guestbilling',
            name='saletime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
