# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20170827_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Authority_Admin',
            field=models.CharField(default='unchecked', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Authority_Customer',
            field=models.CharField(default='unchecked', max_length=100),
            preserve_default=False,
        ),
    ]
