# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20170827_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Authority_AddInventory',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Admin',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Billing',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Customer',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
    ]
