# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20170831_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Val',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=20)),
                ('time_rem', models.IntegerField(default=0)),
                ('con_detail', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_AddInventory',
            field=models.CharField(default=b'checked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Admin',
            field=models.CharField(default=b'checked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Billing',
            field=models.CharField(default=b'checked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Customer',
            field=models.CharField(default=b'checked', max_length=100),
        ),
        migrations.AddField(
            model_name='prod_val',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
    ]
