# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20171027_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Authority_AddInventory',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Admin',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Billing',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Authority_Customer',
            field=models.CharField(default=b'unchecked', max_length=100),
        ),
    ]
