# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20171027_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_val',
            name='gst_in',
            field=models.CharField(default=b'', max_length=15),
        ),
    ]
