# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20171027_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob_number',
            field=models.CharField(max_length=15),
        ),
    ]
