# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20171027_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_id',
            field=models.CharField(default=b'', max_length=100, null=True),
        ),
    ]
